server:
  port: 8080
  tls: false
  certPath: "./ca.pem"
  keyPath: "./key.pem"
  pathPrefix: ""
security:
  tokenSecret: testSecret1234
  allowedOrigins: "*"
database:
  databaseType: "postgres"
  username: "postgres"
  password: "postgres"
  host: "localhost"
  port: 5432
  databaseName: "pingmaster"
  timeoutInSeconds: 20
  maxConcurrentQueries: 100