server:
  port: 8080
  tls: false
  certPath: "./ca.pem"
  keyPath: "./key.pem"
  pathPrefix: "/pingmaster"
database:
  databaseType: "postgres"
  username: "postgres"
  password: "postgres"
  host: "localhost"
  port: 5432
  databaseName: "pingmaster"
  timeoutInSeconds: 20